version: '3.8'
services:
  generator:
    restart: always
    deploy:
      mode: replicated
      replicas: 0
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['4']
            capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data:rw
    build: generator
    environment:
      - TZ=Europe/Moscow
      # - N_PREDICTIONS=1

  upscaler:
    restart: always
    deploy:
      mode: replicated
      replicas: 0
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['5']
            capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data:rw
    build: upscaler
    environment:
      - TZ=Europe/Moscow
      # - RATIO=4

  server:
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data:rw
    build: server
    ports:
      - "10000:10000"
    environment:
      - TZ=Europe/Moscow
      - PORT=10000
